
import lemon from "./images/lemon.png";
import Building from "./images/building.png";
import Mick from "./images/mick.png";
import earth from "./images/earth.png";

export type HTML_TAGS =
    | "html"
    | "head"
    | "title"
    | "meta"
    | "link"
    | "style"
    | "body"
    | "header"
    | "footer"
    | "nav"
    | "main"
    | "section"
    | "article"
    | "aside"
    | "h1"
    | "h2"
    | "h3"
    | "h4"
    | "h5"
    | "h6"
    | "p"
    | "span"
    | "div"
    | "a"
    | "ul"
    | "ol"
    | "li"
    | "img"
    | "figure"
    | "figcaption"
    | "table"
    | "thead"
    | "tbody"
    | "tfoot"
    | "tr"
    | "th"
    | "td"
    | "col"
    | "colgroup"
    | "button"
    | "input"
    | "textarea"
    | "select"
    | "option"
    | "optgroup"
    | "label"
    | "fieldset"
    | "legend"
    | "form"
    | "script"
    | "noscript"
    | "iframe"
    | "embed"
    | "object"
    | "param"
    | "audio"
    | "video"
    | "source"
    | "track"
    | "canvas"
    | "svg"
    | "path"
    | "circle"
    | "rect"
    | "line"
    | "polyline"
    | "polygon"
    | "text"
    | "g"
    | "defs"
    | "symbol"
    | "use"
    | "marker"
    | "clippath"
    | "mask"
    | "textarea"
    | "progress"
    | "meter"
    | "details"
    | "summary"
    | "dialog";

export const Children_Type = {
    string: "",
};

export const sections = ["About", "Experience", "Projects", "Skills", "Contact"];
export const imageArr = [earth, Building, lemon, Mick, earth, earth];
